#Define channels below
# id is the channel id
# name is the name used ingame to select it.

channels:
  1:
    id:
    name:
  2:
    id:
    name:
  3:
    id:
    name:
  4:
    id:
    name:
  5:
    id:
    name:

channel-amount: 2

bot:
  token: ''
  prefix: '~'
  currentserver: ''
  broadcastrole: ''