name: IdissyDiscordAnnouncements
author: dahpr0gam3r
main: me.dahpr0gam3r.IdissyDiscordAnnouncements.Main
version: 1.1.1
depend: [IdissyCore,Discord-ProgramBot-API]

commands:
  discordannounce:
    description: Announces message to the discord channel provided
    usage: /<command> channel message
    aliases: [dannounce]
permissions:
  idissydiscordannouncements.announce:
    default: op